name: Mayhem on Linux (Bazel-based)
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      mayhem_url:
        description: 'Mayhem URL'
        required: true
        default: 'https://app.mayhem.security'


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MAYHEM_URL: ${{ github.event.inputs.mayhem_url || 'https://app.mayhem.security' }}
  MAYHEM_TOKEN: ${{ secrets.MAYHEM_TOKEN }}

jobs:
  build:
    name: '${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [false]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            triplet: x64-linux

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prep Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Run Bazel for Mayhem with Docker image
        run: |
          bazel run --config=libfuzzer //mayhem:run_fuzz_calculator_image
        shell: bash
        env:
          MAYHEM_URL: ${{ env.MAYHEM_URL }}
          XDG_CONFIG_HOME: ${{ env.XDG_CONFIG_HOME }}


      - name: Run bazel for Mayhem package
        run: |
          bazel run //mayhem:run_test_calculator_package
        shell: bash
        env:
          MAYHEM_URL: ${{ env.MAYHEM_URL }}
          XDG_CONFIG_HOME: ${{ env.XDG_CONFIG_HOME }}

      # - name: Run coverage manually
      #   run: |
      #     bazel build //test:download_combined_test_calculator_results
      #     for test in $(ls ./bazel-bin/test/combined_test_calculator-pkg/testsuite); do bazel coverage --combined_report=lcov //test:combined_test_calculator --test_arg=test/combined_test_calculator-pkg/testsuite/$test; done
      #   shell: bash
      #   env:
      #     MAYHEM_URL: ${{ env.MAYHEM_URL }}
      #     XDG_CONFIG_HOME: ${{ env.XDG_CONFIG_HOME }}
